"""support free-text riddle answers

Revision ID: 2477c778b692
Revises: 1d1efdbdf73f
Create Date: 2026-09-30 19:40:59.385969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2477c778b692'
down_revision = '1d1efdbdf73f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('correct_answer',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=300),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('correct_answer',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###
