"""persistent event challenges and audit records

Revision ID: 66d5f8c67ffe
Revises: c49d61f0d62a
Create Date: 2026-10-01 02:24:11.601977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66d5f8c67ffe'
down_revision = 'c49d61f0d62a'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table("admin") as batch_op:
        batch_op.add_column(sa.Column("active", sa.Boolean(), nullable=False, server_default=sa.true()))
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('results_published', sa.Boolean(), nullable=False),
    sa.Column('results_locked', sa.Boolean(), nullable=False),
    sa.Column('leaderboard_visible', sa.Boolean(), nullable=False),
    sa.Column('final_question_count', sa.Integer(), nullable=False),
    sa.Column('round_1_points', sa.Integer(), nullable=False),
    sa.Column('round_3_destination', sa.String(length=300), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rate_bucket',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('window', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('quiz_question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quiz_id', 'position'),
    sa.UniqueConstraint('quiz_id', 'question_id')
    )
    with op.batch_alter_table('quiz_question', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quiz_question_quiz_id'), ['quiz_id'], unique=False)

    op.create_table('desktop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('qr_id', sa.Integer(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['qr_id'], ['qr_challenge.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('qr_id')
    )
    op.create_table('desktop_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('desktop_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('password_attempts', sa.Integer(), nullable=False),
    sa.Column('password_solved', sa.Boolean(), nullable=False),
    sa.Column('final_challenge_unlocked', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('password_attempts BETWEEN 0 AND 3', name='ck_password_attempt_cap'),
    sa.ForeignKeyConstraint(['desktop_id'], ['desktop.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id')
    )
    with op.batch_alter_table('desktop_session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_desktop_session_desktop_id'), ['desktop_id'], unique=False)

    op.create_table('final_assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('questions', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id')
    )
    op.create_table('qr_scan_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('qr_id', sa.Integer(), nullable=True),
    sa.Column('round_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('user_agent', sa.String(length=300), nullable=False),
    sa.ForeignKeyConstraint(['qr_id'], ['qr_challenge.id'], ),
    sa.ForeignKeyConstraint(['round_id'], ['round.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('qr_scan_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_qr_scan_event_qr_id'), ['qr_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_qr_scan_event_round_id'), ['round_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_qr_scan_event_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_qr_scan_event_team_id'), ['team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_qr_scan_event_timestamp'), ['timestamp'], unique=False)

    op.create_table('quiz_attempt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assignments', sa.JSON(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id')
    )
    op.create_table('final_answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['final_assignment.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assignment_id', 'question_id')
    )
    with op.batch_alter_table('final_answer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_final_answer_assignment_id'), ['assignment_id'], unique=False)

    op.create_table('password_attempt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('correct', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('number BETWEEN 1 AND 3'),
    sa.ForeignKeyConstraint(['session_id'], ['desktop_session.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'number')
    )
    with op.batch_alter_table('password_attempt', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_attempt_session_id'), ['session_id'], unique=False)

    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('request_id', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_activity_log_team_id'), ['team_id'], unique=False)
        batch_op.create_foreign_key('fk_activity_team', 'team', ['team_id'], ['id'])

    with op.batch_alter_table('qr_challenge', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quiz_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_qr_quiz', 'quiz', ['quiz_id'], ['id'])
        batch_op.add_column(sa.Column('title', sa.String(length=120), nullable=False, server_default=sa.text("''")))
        batch_op.add_column(sa.Column('clue', sa.Text(), nullable=False, server_default=sa.text("''")))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')))

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kind', sa.String(length=30), nullable=False, server_default=sa.text("'MCQ'")))
        batch_op.add_column(sa.Column('position', sa.Integer(), nullable=False, server_default=sa.text('0')))

    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.String(length=30), nullable=False, server_default=sa.text("'REGISTERED'")))
        batch_op.add_column(sa.Column('assigned_qr_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('bonus', sa.Integer(), nullable=False, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('penalty', sa.Integer(), nullable=False, server_default=sa.text('0')))
        batch_op.create_index(batch_op.f('ix_team_state'), ['state'], unique=False)
        batch_op.create_foreign_key('fk_team_assigned_qr', 'qr_challenge', ['assigned_qr_id'], ['id'])

    op.execute(sa.text("INSERT INTO event (id, name, mode, active, results_published, results_locked, leaderboard_visible, final_question_count, round_1_points, round_3_destination, version) VALUES (1, 'Swayambhu 2026', 'TEST', false, false, false, false, 10, 0, 'Contact the coordinator for your desktop station.', 0)"))
    op.execute(sa.text("UPDATE round SET status='ENDED' WHERE status='COMPLETED'"))
    op.execute(sa.text("UPDATE round SET name='Desktop Final Challenge' WHERE number=3"))
    op.execute(sa.text("INSERT INTO qr_scan_event (team_id, qr_id, round_id, timestamp, status, ip_address, user_agent) SELECT team_id, qr_id, round_id, scan_time, 'VALID', '', 'legacy import' FROM scan_log"))
    # ### end Alembic commands ###


def downgrade():
    with op.batch_alter_table("admin") as batch_op:
        batch_op.drop_column("active")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint('fk_team_assigned_qr', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_team_state'))
        batch_op.drop_column('penalty')
        batch_op.drop_column('bonus')
        batch_op.drop_column('assigned_qr_id')
        batch_op.drop_column('state')

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_column('position')
        batch_op.drop_column('kind')

    with op.batch_alter_table('qr_challenge', schema=None) as batch_op:
        batch_op.drop_constraint('fk_qr_quiz', type_='foreignkey')
        batch_op.drop_column('quiz_id')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('clue')
        batch_op.drop_column('title')

    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint('fk_activity_team', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_activity_log_team_id'))
        batch_op.drop_column('request_id')
        batch_op.drop_column('team_id')

    with op.batch_alter_table('password_attempt', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_attempt_session_id'))

    op.drop_table('password_attempt')
    with op.batch_alter_table('final_answer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_final_answer_assignment_id'))

    op.drop_table('final_answer')
    op.drop_table('quiz_attempt')
    with op.batch_alter_table('qr_scan_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_qr_scan_event_timestamp'))
        batch_op.drop_index(batch_op.f('ix_qr_scan_event_team_id'))
        batch_op.drop_index(batch_op.f('ix_qr_scan_event_status'))
        batch_op.drop_index(batch_op.f('ix_qr_scan_event_round_id'))
        batch_op.drop_index(batch_op.f('ix_qr_scan_event_qr_id'))

    op.drop_table('qr_scan_event')
    op.drop_table('final_assignment')
    with op.batch_alter_table('desktop_session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_desktop_session_desktop_id'))

    op.drop_table('desktop_session')
    op.drop_table('desktop')
    with op.batch_alter_table('quiz_question', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quiz_question_quiz_id'))

    op.drop_table('quiz_question')
    op.drop_table('rate_bucket')
    op.drop_table('quiz')
    op.drop_table('event')
    # ### end Alembic commands ###
